[package]
name = "cream"
version = "0.2.0"
edition = "2021"

[dependencies]
serde_json = "1.0.104"
rusty_v8 = "0.32.1"
colored = "2.0.4"
ureq = "2.7.1"

[profile.release]
codegen-units = 1
opt-level = "s"
strip = true
lto = true
