pub const DEFAULT_ERROR_RESPONSE: &str = "<pre style=\"word-wrap: break-word; white-space: pre-wrap;\">404 page not found</pre>";
pub const NOT_FOUND_RESPONSE_FILE: &str = "./build/error.html";
pub const DEFAULT_COMPILATION_PATH: &str = "./build/dist.html";
pub const ROUTER_TOKEN: &str = "<Router route=";
pub const IC_TOKEN: &str = "import component";
pub const CONFIG_FILE: &str = "./config.dsp";
pub const RENDER_COMPONENT: &str = "Render";
pub const BUILT_JS: &str = "./build/.$.js";
pub const IGNORE_STATE: &str = " //!state";
pub const ERROR_COMPONENT: &str = "Error";
pub const UNTIL_TOKEN: &str = "<Until ";
pub const NEW_LINE_CHAR: char = '\n';
pub const SINGLE_QUOTE: char = '\'';
pub const FROM_TOKEN: &str = "from";
pub const ROUTER_TOKEN_LEN: usize = 14;
pub const FROM_TOKEN_LEN: usize = 4;
pub const DOUBLE_QUOTE: char = '"';
pub const BACK_TICK: char = '`';
pub const IC_TOKEN_LEN: usize = 16;
pub const SBF_AS_STR: &str = "{";
pub const NEW_LINE: &str = "\n";
pub const CAM: &str = ":cam";
pub const SPACE: &str = " ";
pub const NUL: char = '\0';
pub const SBF: char = '{';
pub const SBS: char = '}';
pub const NIL: &str = "";
